// libs/react/src/lib/createApp.tsx
import {
  Application,
  ApplicationConstructor,
  MicrozordLifecycleEvent,
  MicrozordMessageEvent,
} from '@microzord/core';
import {Root, createRoot} from 'react-dom/client';
import {ReactElement} from 'react';

export function createApp<P>(
  name: string,
  element: ReactElement<P>,
): ApplicationConstructor {
  class ReactApplication extends Application {
    private root: Root | undefined;
    async bootstrap(container: string | Element, props?: Record<string, unknown>) {
      container =
        typeof container === 'string' ? document.querySelector(container)! : container;

      this.root = createRoot(container);
      await super.bootstrap(container, props);

      this.root.render(element);
      //https://github.com/reactwg/react-18/discussions/5#discussioncomment-796012
      requestIdleCallback(() => {
        this.emitHook(MicrozordLifecycleEvent.bootstrapped());
      });
    }

    destroy() {
      super.destroy();

      if (this.root) {
        this.root.unmount();
      }
      this.container = '';

      this.emitHook(MicrozordLifecycleEvent.destroyed());
    }

    async navigate(_url: string, _props: unknown | undefined): Promise<void> {
      return undefined;
    }

    async send(_msg: string | MicrozordMessageEvent): Promise<void> {
      return undefined;
    }
  }

  document.dispatchEvent(
    new CustomEvent('microzord:load', {
      detail: {name, appConstructor: ReactApplication},
    }),
  );

  return ReactApplication;
}

// libs/angular/child/src/create-app.ts
import {CompilerOptions, InjectFlags, InjectionToken, NgModuleRef} from '@angular/core';
import {Application, ApplicationConstructor} from '@microzord/core';
import {Router} from '@angular/router';
import {MicrozordLifecycleEvent, MicrozordMessageEvent} from '@microzord/core';

export const APP_NAME = new InjectionToken<string>('App name');
export const ROOT_SELECTOR = new InjectionToken<string>('Root selector');

// todo: очень грубая имплементация
export function createApp<
  TModule,
  Props extends Record<string, unknown> = Record<string, unknown>,
>(
  bootstrapFn: (props?: CompilerOptions) => Promise<NgModuleRef<TModule>>,
  rootSelector: string,
): ApplicationConstructor {
  // todo: не хватает имплементации хуков, сообщений и навигации
  class AngularApp<T extends Record<string, unknown> = Props> extends Application<T> {
    private router: Router | null = null;
    private ngModule: NgModuleRef<TModule> | null = null;

    destroy() {
      super.destroy();

      if (this.ngModule) {
        this.ngModule.destroy();
        this.ngModule = null;
      }

      this.emitHook(MicrozordLifecycleEvent.destroyed());
    }

    async bootstrap(container: string | Element, props?: T): Promise<void> {
      const containerElement =
        typeof container === 'string' ? document.querySelector(container) : container;

      if (!containerElement) {
        throw new Error(`No container found for ${container}`);
      }

      const rootElement = document.createElement(rootSelector);

      containerElement.appendChild(rootElement);

      this.ngModule = await bootstrapFn(props);
      this.router = this.ngModule.injector.get(Router, null, InjectFlags.Optional);

      await super.bootstrap(container, props);

      this.emitHook(MicrozordLifecycleEvent.bootstrapped());
    }

    async navigate(url: string, _props: unknown | undefined): Promise<void> {
      if (this.router) {
        await this.router.navigateByUrl(url);
      }
    }

    async send(_msg: string | MicrozordMessageEvent): Promise<void> {
      //
    }
  }

  return AngularApp;
}
